
<?php

function lang($sentencia){

    //SYSTEM    if($sentencia == "Saved vulnerability" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidad guardada";};
    if($sentencia == "Edit asset" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar objetivo";};
    if($sentencia == "Objectives details" && $_SESSION['idioma'] == "ES"){ $sentencia = "Detalles de los objetivos";};
    if($sentencia == "At the moment we will have to manually insert a graphic or image." && $_SESSION['idioma'] == "ES"){ $sentencia = "Por el momento deberemos insertar manualmente un gráfico o imagen.";};
    if($sentencia == "Delete" && $_SESSION['idioma'] == "ES"){ $sentencia = "Eliminar";};
    if($sentencia == "Vulnerability images" && $_SESSION['idioma'] == "ES"){ $sentencia = "Imágenes de vulnerabilidad";};
    if($sentencia == "Manage vulnerabilities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Gestionar vulnerabilidades";};
    if($sentencia == "Search Vulnerabilities..." && $_SESSION['idioma'] == "ES"){ $sentencia = "Buscar Vulnerabilidades...";};
    if($sentencia == "Order" && $_SESSION['idioma'] == "ES"){ $sentencia = "Orden";};
    if($sentencia == "Add vulns" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir vulns";};
    if($sentencia == "Add image" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir imagen";};
    if($sentencia == "Edit values" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar valores";};
    if($sentencia == "Vulnerabilities associated with" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidades asociadas a";};
    if($sentencia == "Are you interested in cybersecurity?" && $_SESSION['idioma'] == "ES"){ $sentencia = "Estás interesado en ciberseguridad?";};
    if($sentencia == "Go now" && $_SESSION['idioma'] == "ES"){ $sentencia = "Ver ahora";};
    if($sentencia == "Visit all my links!" && $_SESSION['idioma'] == "ES"){ $sentencia = "Visita todos mis links!";};
    if($sentencia == "Report Objectives" && $_SESSION['idioma'] == "ES"){ $sentencia = "Objetivos de la auditoría";};
    if($sentencia == "Add objective" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir objetivo";};
    if($sentencia == "Add objectives" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir objetivos";};
    if($sentencia == "Objectives" && $_SESSION['idioma'] == "ES"){ $sentencia = "Objetivos";};
    if($sentencia == "Deadline" && $_SESSION['idioma'] == "ES"){ $sentencia = "Fecha de entrega";};
    if($sentencia == "Saved vulnerability" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidad guardada";};
    if($sentencia == "Account settings" && $_SESSION['idioma'] == "ES"){ $sentencia = "Ajustes de cuenta";};
    if($sentencia == "System Member" && $_SESSION['idioma'] == "ES"){ $sentencia = "Usuario de sistema";};
    if($sentencia == "Dashboard" && $_SESSION['idioma'] == "ES"){ $sentencia = "Dashboard";};
    if($sentencia == "Navigation" && $_SESSION['idioma'] == "ES"){ $sentencia = "Navegación";};
    if($sentencia == "Search Reports" && $_SESSION['idioma'] == "ES"){ $sentencia = "Buscar Informes";};
    if($sentencia == "Profile" && $_SESSION['idioma'] == "ES"){ $sentencia = "Perfil";};
    if($sentencia == "Log out" && $_SESSION['idioma'] == "ES"){ $sentencia = "Cerrar sesión";};
    if($sentencia == "Settings" && $_SESSION['idioma'] == "ES"){ $sentencia = "Ajustes";};
    if($sentencia == "Messages" && $_SESSION['idioma'] == "ES"){ $sentencia = "Mensajes";};
    if($sentencia == "Now" && $_SESSION['idioma'] == "ES"){ $sentencia = "Ahora";};
    if($sentencia == "Create New Report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Crear Nuevo Informe";};
    if($sentencia == "Vulnerabilities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidades";};
    if($sentencia == "Audited Client" && $_SESSION['idioma'] == "ES"){ $sentencia = "Clientes registrados";};
    if($sentencia == "Auditors" && $_SESSION['idioma'] == "ES"){ $sentencia = "Auditores";};
    if($sentencia == "Report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Informe";};
    if($sentencia == "Reports" && $_SESSION['idioma'] == "ES"){ $sentencia = "Informes";};
    if($sentencia == "Report Vulnerabilities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidades reportadas";};
    if($sentencia == "Vulns in database" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulns en base de datos";};
    if($sentencia == "Free Hacking reporting tool from " && $_SESSION['idioma'] == "ES"){ $sentencia = "Herramienta gratuita de reporting, creada por: ";};
    if($sentencia == "List of vulnerabilities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Listado de vulnerabilidades";};
    if($sentencia == "List" && $_SESSION['idioma'] == "ES"){ $sentencia = "Listado";};
    if($sentencia == "Description" && $_SESSION['idioma'] == "ES"){ $sentencia = "Descripción";};
    if($sentencia == "Description image" && $_SESSION['idioma'] == "ES"){ $sentencia = "Descripción de la imágen";};
    if($sentencia == "Criticality" && $_SESSION['idioma'] == "ES"){ $sentencia = "Criticidad";};
    if($sentencia == "Low" && $_SESSION['idioma'] == "ES"){ $sentencia = "Baja";};
    if($sentencia == "Medium" && $_SESSION['idioma'] == "ES"){ $sentencia = "Media";};
    if($sentencia == "High" && $_SESSION['idioma'] == "ES"){ $sentencia = "Alta";};
    if($sentencia == "Very High" && $_SESSION['idioma'] == "ES"){ $sentencia = "Muy Alta";};
    if($sentencia == "Edit" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar";};
    if($sentencia == "Remove" && $_SESSION['idioma'] == "ES"){ $sentencia = "Eliminar";};
    if($sentencia == "Search vulnerabilities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Buscar vulnerabilidades";};
    if($sentencia == "NIST calculator" && $_SESSION['idioma'] == "ES"){ $sentencia = "Calculadora NIST";};
    if($sentencia == "Edit Vulnerability" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar vulnerabilidad";};
    if($sentencia == "Effort" && $_SESSION['idioma'] == "ES"){ $sentencia = "Esfuerzo";};
    if($sentencia == "Audit section" && $_SESSION['idioma'] == "ES"){ $sentencia = "Sección auditoria";};
    if($sentencia == "Internal audit" && $_SESSION['idioma'] == "ES"){ $sentencia = "Auditoría interna";};
    if($sentencia == "External audit" && $_SESSION['idioma'] == "ES"){ $sentencia = "Auditoría externa";};
    if($sentencia == "Wifi audit" && $_SESSION['idioma'] == "ES"){ $sentencia = "Auditoría wifi";};
    if($sentencia == "Solution" && $_SESSION['idioma'] == "ES"){ $sentencia = "Solución";};
    if($sentencia == "Recommendation for criticality table" && $_SESSION['idioma'] == "ES"){ $sentencia = "Recomendación para tabla de criticidad";};
    if($sentencia == "Add vulnerability" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir vulnerabilidad";};
    if($sentencia == "Delete vulnerability" && $_SESSION['idioma'] == "ES"){ $sentencia = "Eliminar vulnerabilidad";};
    if($sentencia == "Vulnerability removed from the system" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidad eliminada del sistema";};
    if($sentencia == "Return" && $_SESSION['idioma'] == "ES"){ $sentencia = "Volver";};
    if($sentencia == "Customers" && $_SESSION['idioma'] == "ES"){ $sentencia = "Clientes";};
    if($sentencia == "List of customers" && $_SESSION['idioma'] == "ES"){ $sentencia = "Listado de clientes";};
    if($sentencia == "Search customers" && $_SESSION['idioma'] == "ES"){ $sentencia = "Buscar clientes";};
    if($sentencia == "Name" && $_SESSION['idioma'] == "ES"){ $sentencia = "Nombre";};
    if($sentencia == "Web page" && $_SESSION['idioma'] == "ES"){ $sentencia = "Página web";};
    if($sentencia == "Logo" && $_SESSION['idioma'] == "ES"){ $sentencia = "Logo";};
    if($sentencia == "Edit company" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar empresa";};
    if($sentencia == "Links and subdomains" && $_SESSION['idioma'] == "ES"){ $sentencia = "Links y subdominios";};
    if($sentencia == "Domain" && $_SESSION['idioma'] == "ES"){ $sentencia = "Dominio";};
    if($sentencia == "Email" && $_SESSION['idioma'] == "ES"){ $sentencia = "Correo";};
    if($sentencia == "Name and surname" && $_SESSION['idioma'] == "ES"){ $sentencia = "Nombre y apellidos";};
    if($sentencia == "Phone" && $_SESSION['idioma'] == "ES"){ $sentencia = "Teléfono";};
    if($sentencia == "Owner data" && $_SESSION['idioma'] == "ES"){ $sentencia = "Datos del propietario";};
    if($sentencia == "Organization" && $_SESSION['idioma'] == "ES"){ $sentencia = "Organización";};
    if($sentencia == "Employee emails" && $_SESSION['idioma'] == "ES"){ $sentencia = "Correos de empleados";};
    if($sentencia == "MX Records" && $_SESSION['idioma'] == "ES"){ $sentencia = "Registros MX";};
    if($sentencia == "Edit profile" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar perfil";};
    if($sentencia == "You have reached the search limit on your hunter.io plan" && $_SESSION['idioma'] == "ES"){ $sentencia = "Ha alcanzado el límite de búsquedas en su plan de hunter.io";};
    if($sentencia == "Add client" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir cliente";};
    if($sentencia == "Your clients" && $_SESSION['idioma'] == "ES"){ $sentencia = "Tus clientes";};
    if($sentencia == "List of reports" && $_SESSION['idioma'] == "ES"){ $sentencia = "Lista de informes";};
    if($sentencia == "Search reports" && $_SESSION['idioma'] == "ES"){ $sentencia = "Buscar informes";};
    if($sentencia == "Report name" && $_SESSION['idioma'] == "ES"){ $sentencia = "Nombre del informe";};
    if($sentencia == "State" && $_SESSION['idioma'] == "ES"){ $sentencia = "Estado";};
    if($sentencia == "Date" && $_SESSION['idioma'] == "ES"){ $sentencia = "Fecha";};
    if($sentencia == "Finalized" && $_SESSION['idioma'] == "ES"){ $sentencia = "Terminado";};
    if($sentencia == "In process" && $_SESSION['idioma'] == "ES"){ $sentencia = "En proceso";};
    if($sentencia == "En proceso" && $_SESSION['idioma'] == "EN"){ $sentencia = "In process";};
    if($sentencia == "Terminado" && $_SESSION['idioma'] == "EN"){ $sentencia = "Finalized";};
    if($sentencia == "Add report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir informe";};
    if($sentencia == "Delete company" && $_SESSION['idioma'] == "ES"){ $sentencia = "Eliminar empresa";};
    if($sentencia == "Company removed from the system" && $_SESSION['idioma'] == "ES"){ $sentencia = "Empresa eliminada del sistema";};
    if($sentencia == "Save this web in .mhtml format and open it in Word to edit the report!!" && $_SESSION['idioma'] == "ES"){ $sentencia = "Guarda esta web en formato .mhtml y abrela en Word para editar el informe!!";};
    if($sentencia == "Document name" && $_SESSION['idioma'] == "ES"){ $sentencia = "Nombre del documento";};
    if($sentencia == "Customer name" && $_SESSION['idioma'] == "ES"){ $sentencia = "Nombre cliente";};
    if($sentencia == "Discharge date" && $_SESSION['idioma'] == "ES"){ $sentencia = "Fecha de alta";};
    if($sentencia == "Edit report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Editar informe";};
    if($sentencia == "State" && $_SESSION['idioma'] == "ES"){ $sentencia = "Estado";};
    if($sentencia == "Recommendations" && $_SESSION['idioma'] == "ES"){ $sentencia = "Recomendaciones";};
    if($sentencia == "Recommendation" && $_SESSION['idioma'] == "ES"){ $sentencia = "Recomendación";};
    if($sentencia == "Conclusions" && $_SESSION['idioma'] == "ES"){ $sentencia = "Conclusiones";};
    if($sentencia == "Proposals" && $_SESSION['idioma'] == "ES"){ $sentencia = "Propuestas";};
    if($sentencia == "Add" && $_SESSION['idioma'] == "ES"){ $sentencia = "Añadir";};
    if($sentencia == "Description" && $_SESSION['idioma'] == "ES"){ $sentencia = "Descripción";};
    if($sentencia == "Section" && $_SESSION['idioma'] == "ES"){ $sentencia = "Sección";};
    if($sentencia == "Save" && $_SESSION['idioma'] == "ES"){ $sentencia = "Guardar";};
    if($sentencia == "Client name" && $_SESSION['idioma'] == "ES"){ $sentencia = "Nombre de cliente";};
    if($sentencia == "Overview report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Generar informe";};
    if($sentencia == "Delete report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Eliminar informe";};
    if($sentencia == "Report removed from the system" && $_SESSION['idioma'] == "ES"){ $sentencia = "Informe eliminado del sistema";};
    if($sentencia == "Recorded vulnerabilities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidades registradas";};
    if($sentencia == "Registered companies" && $_SESSION['idioma'] == "ES"){ $sentencia = "Clientes dados de alta";};
    if($sentencia == "Reports made" && $_SESSION['idioma'] == "ES"){ $sentencia = "Informes realizados";};
    if($sentencia == "Last two reports" && $_SESSION['idioma'] == "ES"){ $sentencia = "Dos últimos informes";};
    if($sentencia == "Date:" && $_SESSION['idioma'] == "ES"){ $sentencia = "Fecha:";};
    if($sentencia == "Vulnerabilities found" && $_SESSION['idioma'] == "ES"){ $sentencia = "Vulnerabilidades encontradas";};


    //REPORT
    if($sentencia == "LEGAL WARNING" && $_SESSION['idioma'] == "ES"){ $sentencia = "AVISO LEGAL";};
    if($sentencia == "This document contains confidential and proprietary information which is for the exclusive use of " && $_SESSION['idioma'] == "ES"){ $sentencia = "Este documento contiene información confidencial y propietaria la cual es de uso exclusivo de ";};
    if($sentencia == "Unauthorized reproduction or use of this document is strictly prohibited." && $_SESSION['idioma'] == "ES"){ $sentencia = "La reproducción o uso no autorizado de este documento está totalmente prohibido.";};
    if($sentencia == "CONTROL DOCUMENT" && $_SESSION['idioma'] == "ES"){ $sentencia = "CONTROL DE DOCUMENTO";};
    if($sentencia == "DOCUMENT:" && $_SESSION['idioma'] == "ES"){ $sentencia = "DOCUMENTO:";};
    if($sentencia == "NAME" && $_SESSION['idioma'] == "ES"){ $sentencia = "NOMBRE";};
    if($sentencia == "AUTHOR:" && $_SESSION['idioma'] == "ES"){ $sentencia = "AUTOR:";};
    if($sentencia == "CUSTOMER:" && $_SESSION['idioma'] == "ES"){ $sentencia = "CLIENTE:";};
    if($sentencia == "CONFIDENTIALITY STATEMENT" && $_SESSION['idioma'] == "ES"){ $sentencia = "DECLARACIÓN DE CONFIDENCIALIDAD";};
    if($sentencia == "This report contains information regarding possible security breaches of " && $_SESSION['idioma'] == "ES"){ $sentencia = "Este informe contiene la información relativa a las posibles brechas de seguridad de ";};
    if($sentencia == "and their systems." && $_SESSION['idioma'] == "ES"){ $sentencia = "y sus sistemas.";};
    if($sentencia == "recommends that special precautions be taken to" && $_SESSION['idioma'] == "ES"){ $sentencia = "recomienda que sean tomadas precauciones especiales para";};
    if($sentencia == " protect the confidentiality of this document and the information contained in it." && $_SESSION['idioma'] == "ES"){ $sentencia = " proteger la confidencialidad de este documento y de la información contenida en él.";};
    if($sentencia == "has maintained and secured a copy of this report for consultation by the" && $_SESSION['idioma'] == "ES"){ $sentencia = "ha mantenido y asegurado una copia de este informe para consulta por parte del";};
    if($sentencia == "All other copies of the report have been delivered to " && $_SESSION['idioma'] == "ES"){ $sentencia = "Todas las demás copias del informe se han entregado a ";};
    if($sentencia == "The security assessment" && $_SESSION['idioma'] == "ES"){ $sentencia = "La evaluación de la seguridad";};
    if($sentencia == "it is an uncertain process, based on experiences, currently available information and known threats." && $_SESSION['idioma'] == "ES"){ $sentencia = "es un proceso incierto, basado en las experiencias, la información actualmente disponible y las amenazas conocidas.";};
    if($sentencia == "It must be understood that all information systems, by their nature, depend on human beings and are vulnerable in some degree." && $_SESSION['idioma'] == "ES"){ $sentencia = "Se debe entender que todos los sistemas de información, por su naturaleza dependen de los seres humanos y son vulnerables en cierto grado.";};
    if($sentencia == "This report" && $_SESSION['idioma'] == "ES"){ $sentencia = "Este informe";};
    if($sentencia == "may recommend that" && $_SESSION['idioma'] == "ES"){ $sentencia = "podrá recomendar que";};
    if($sentencia == "use certain software or hardware products manufactured" && $_SESSION['idioma'] == "ES"){ $sentencia = "utilice ciertos productos de software o hardware fabricados";};
    if($sentencia == "or maintained by other providers. BlackStone bases these recommendations on of your previous experience with the capabilities of these products. However, Blackstone cannot and should not guarantee that any particular product will perform as advertised by the seller." && $_SESSION['idioma'] == "ES"){ $sentencia = "o mantenidas por otros proveedores. BlackStone  basa estas recomendaciones a partir de su experiencia previa con las capacidades de estos productos. Sin embargo, BlackStone no puede y no debe garantizar que un determinado producto funcionará según lo anunciado por el vendedor. ";};
    if($sentencia == "INDEX" && $_SESSION['idioma'] == "ES"){ $sentencia = "ÍNDICE";};
    if($sentencia == "(GENERATE INDEX WITH WORD)" && $_SESSION['idioma'] == "ES"){ $sentencia = "(GENERAR INDICE CON WORD)";};
    if($sentencia == "INTRODUCTION" && $_SESSION['idioma'] == "ES"){ $sentencia = "INTRODUCCIÓN";};
    if($sentencia == "During the tests, the activities that a real attacker would carry out are simulated, discovering the vulnerabilities, their level of risk, and generating recommendations that allow the client to carry out the remediation of these. Each section of this report details important aspects of how an attacker could use the vulnerability to compromise and gain unauthorized access to sensitive information. Are included In addition, guidelines that, when applied, will improve the levels of confidentiality, integrity and availability of the analyzed systems." && $_SESSION['idioma'] == "ES"){ $sentencia = "Durante las pruebas se simulan las actividades que realizaría un atacante real, descubriendo las vulnerabilidades, su nivel de riesgo, y generando recomendaciones que permitan al cliente realizar la remediación de estas. En cada sección de este informe se detallan los aspectos importantes de la forma en que un atacante podría utilizar la vulnerabilidad para comprometer y obtener acceso no autorizado a información sensible. Se incluyen además directrices que al ser aplicadas mejoraran los niveles de confidencialidad, integridad y disponibilidad de los sistemas analizados.";};
    if($sentencia == "Vulnerability scans and ethical hacking tests were conducted by BlackStone's Red Team during the approved dates. The ethical hacking tests did not explicitly attempt to execute denial-of-service exploits and all of them were carried out without knowledge of users or passwords on the network." && $_SESSION['idioma'] == "ES"){ $sentencia = "Los análisis de vulnerabilidades y pruebas de hacking ético fueron realizados por el equipo de Red Team de BlackStone  durante las fechas aprobadas. Las pruebas de hacking ético no intentaron explícitamente la ejecución de exploits que implicaran denegación de servicio y todas ellas se realizaron sin conocimiento de usuarios o contraseñas en la red.";};
    if($sentencia == "OBJECTIVE" && $_SESSION['idioma'] == "ES"){ $sentencia = "OBJETIVO";};
    if($sentencia == "The objective of the security evaluation is to detect the existing security vulnerabilities in the analyzed systems in order to subsequently generate a report with the findings and recommendations that allow their remediation." && $_SESSION['idioma'] == "ES"){ $sentencia = "El objetivo de la evaluación de seguridad es detectar las vulnerabilidades de seguridad existentes en los sistemas analizados para posteriormente generar un informe con los hallazgos y recomendaciones que permitan la remediación de estas.";};
    if($sentencia == "SCOPE" && $_SESSION['idioma'] == "ES"){ $sentencia = "ALCANCE";};
    if($sentencia == "The evaluation carried out has focused on the objectives approved in the scope of the contract, which establishes:" && $_SESSION['idioma'] == "ES"){ $sentencia = "La evaluación realizada se ha centrado en los objetivos aprobados en el alcance del contrato, en el cual se establece:";};
    if($sentencia == "Description activities" && $_SESSION['idioma'] == "ES"){ $sentencia = "Descripción de actividades";};
    if($sentencia == "EXECUTIVE SUMMARY" && $_SESSION['idioma'] == "ES"){ $sentencia = "RESUMEN EJECUTIVO";};
    if($sentencia == "TEST RESULTS" && $_SESSION['idioma'] == "ES"){ $sentencia = "RESULTADO DE LAS PRUEBAS";};
    if($sentencia == "CONCLUSIONS" && $_SESSION['idioma'] == "ES"){ $sentencia = "CONCLUSIONES";};
    if($sentencia == "RECOMMENDATIONS" && $_SESSION['idioma'] == "ES"){ $sentencia = "RECOMENDACIONES";};
    if($sentencia == "Infrastructure improvement proposals" && $_SESSION['idioma'] == "ES"){ $sentencia = "Propuestas de mejora sobre la infraestructura";};
    if($sentencia == "Criticality table" && $_SESSION['idioma'] == "ES"){ $sentencia = "Tabla de criticidad";};
    if($sentencia == "Recommendation" && $_SESSION['idioma'] == "ES"){ $sentencia = "Recomendación";};
    if($sentencia == "DOCUMENT CONTROL" && $_SESSION['idioma'] == "ES"){ $sentencia = "CONTROL DE DOCUMENTO";};
    if($sentencia == "Vulnerability" && $_SESSION['idioma'] == "ES"){ $sentencia = "vulnerabilidad";};
    if($sentencia == "Amount" && $_SESSION['idioma'] == "ES"){ $sentencia = "Cantidad";};
    if($sentencia == "Percentage" && $_SESSION['idioma'] == "ES"){ $sentencia = "Porcentaje";};
    if($sentencia == "Critics" && $_SESSION['idioma'] == "ES"){ $sentencia = "Críticas";};
    if($sentencia == "Penetration Test Report for" && $_SESSION['idioma'] == "ES"){ $sentencia = "Informe de Pentesting para";};
    if($sentencia == "YOU CAN MAKE REPORTS ON AUDITS AND CERTIFICATION EXAMS WITH THE FREE REPORTING TOOL FOR KALI AND PARROT" && $_SESSION['idioma'] == "ES"){ $sentencia = "PUEDES REALIZAR INFORMES DE AUDITORÍAS Y EXÁMENES DE CERTIFICACIONES CON LA HERRAMIENTA GRATUITA DE REPORTING PARA KALI Y PARROT";};


    if($sentencia == "You have to capture a screenshot of this graphic to insert it into Word." && $_SESSION['idioma'] == "ES"){ $sentencia = "Tienes que capturar pantalla de este gráfico para insertarlo dentro del Word.";};

    return $sentencia;
};

?>
